on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello from node
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: uses local action
        uses: ./.github/actions
